env:
  browser: true
  es2020: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: [
      "./tsconfig.json",
      "./tsconfig.app.json",
      # "./tsconfig.base.json",
      "./tsconfig.spec.json",
    ]
plugins:
  - "@typescript-eslint"
rules:
  # Possible Errors
  no-console: warn

  # Best Practices
  dot-notation: error
  no-param-reassign: error
  no-return-await: off
  no-unused-expressions: error
  radix: error

  # Strict Mode

  # Variables
  no-unused-vars: off
  no-shadow: off

  # Node.js and CommonJS

  # Stylistic Issues
  camelcase: off
  comma-dangle:
    - error
    - never
  max-len:
    - warn
    - code: 140
      ignoreComments: true
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreTrailingComments: true
      ignoreUrls: true
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - blocks: never
      classes: always
      switches: never
  eol-last: error
  indent:
    - error
    - 2
  space-before-function-paren: error
  quotes:
    - error
    - single

  # ECMAScript 6 and configs imported from extends: 'eslint:recommended'
  no-var: error
  prefer-template: error

  complexity: off
  curly: error
  object-curly-spacing:
    - error
    - always
  eqeqeq:
    - error
    - smart
  for-direction: error
  getter-return: error
  guard-for-in: error
  id-blacklist:
    - error
    - any
      Number
      number
      String
      string
      Boolean
      boolean
      Undefined
      undefined
  id-match: error
  max-classes-per-file: off
  new-parens: error
  no-array-constructor: off
  no-async-promise-executor: error
  no-bitwise: error
  no-caller: error
  no-case-declarations: error
  no-class-assign: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-const-assign: error
  no-constant-condition: error
  no-debugger: error
  no-delete-var: error
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-else-if: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty: off
  no-empty-character-class: error
  no-empty-function: off
  no-empty-pattern: error
  no-eval: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-semi: off
  semi: error
  no-fallthrough: error
  no-func-assign: error
  no-global-assign: error
  no-import-assign: error
  no-inner-declarations: error
  no-invalid-regexp: error
  no-invalid-this: off
  no-irregular-whitespace: error
  no-misleading-character-class: error
  no-mixed-spaces-and-tabs: error
  no-new-symbol: error
  no-new-wrappers: error
  no-obj-calls: error
  no-octal: error
  no-prototype-builtins: error
  no-redeclare: error
  no-regex-spaces: error
  no-restricted-imports:
    - error
    - rxjs/Rx
  no-self-assign: error
  no-setter-return: error
  no-shadow-restricted-names: error
  no-sparse-arrays: error
  no-this-before-super: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  no-unused-labels: error
  no-useless-catch: error
  no-useless-constructor: off
  no-useless-escape: error
  no-with: error
  object-shorthand: error
  one-var:
    - error
    - never
  prefer-const: error
  quote-props:
    - error
    - as-needed
  require-yield: error
  spaced-comment:
    - error
    - always
  use-isnan: error
  valid-typeof: error
  no-multiple-empty-lines:
    - error
    - max: 1
  space-in-parens: error
  space-before-blocks: error
  keyword-spacing: error

  # Typescript
  "@typescript-eslint/adjacent-overload-signatures": error
  "@typescript-eslint/array-type":
    - error
    - array: true
  "@typescript-eslint/ban-types":
    - error
    - types:
        any: null
  "@typescript-eslint/naming-convention":
    - error
    - selector: "variable"
      format: ["strictCamelCase", "snake_case", "UPPER_CASE"]
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: false
      allowHigherOrderFunctions: true
  "@typescript-eslint/member-delimiter-style": error
  "@typescript-eslint/no-array-constructor": error
  "@typescript-eslint/no-empty-interface": error
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-misused-new": error
  "@typescript-eslint/no-magic-numbers":
    - warn
    - ignoreEnums: true
      ignoreNumericLiteralTypes: true
      ignore:
        - -1
        - 0
        - 1
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/no-non-null-assertion": error
  "@typescript-eslint/no-useless-constructor": error
  "@typescript-eslint/no-use-before-define": error
  "@typescript-eslint/prefer-includes": error
  "@typescript-eslint/promise-function-async":
    - error
    - checkArrowFunctions: false
  "@typescript-eslint/type-annotation-spacing": error
  "@typescript-eslint/unified-signatures": error

  "@typescript-eslint/ban-ts-comment": error
  "@typescript-eslint/consistent-type-assertions":
    - error
    - assertionStyle: angle-bracket
  "@typescript-eslint/explicit-module-boundary-types": warn
  "@typescript-eslint/member-ordering": error
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-inferrable-types":
    - error
    - ignoreParameters: true
  "@typescript-eslint/no-parameter-properties": off
  "@typescript-eslint/no-this-alias": error
  "@typescript-eslint/no-unused-expressions": error
  "@typescript-eslint/prefer-as-const": error
  "@typescript-eslint/prefer-for-of": error
  "@typescript-eslint/prefer-namespace-keyword": error
